name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
  pull_request:

# Skip tests if only documentation files changed
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docs:
              - 'README.md'
              - 'ACT_TESTING_GUIDE.md'
              - 'MIGRATION_SUMMARY.md'
              - 'TESTS_TODO.md'
              - 'docs/**'
              - '*.md'

  test:
    needs: changes
    if: ${{ !needs.changes.outputs.docs }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Test
        uses: docker/bake-action@v6
        with:
          source: .
          targets: test
      -
        name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
